/*******************************************************************************
 * Copyright 2012-2013 Trento RISE
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 ******************************************************************************/
package smartcampus.service.trentomale.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrainViewService", targetNamespace = "TrainViewServiceNs")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrainViewService {


    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GertServerTime", action = "TrainViewServiceNs/TrainViewService/GertServerTime")
    @WebResult(name = "GertServerTimeResult", targetNamespace = "TrainViewServiceNs")
    @RequestWrapper(localName = "GertServerTime", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GertServerTime")
    @ResponseWrapper(localName = "GertServerTimeResponse", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GertServerTimeResponse")
    public XMLGregorianCalendar gertServerTime();

    /**
     * 
     * @return
     *     returns smartcampus.service.trentomale.wsclient.ArrayOfStation
     */
    @WebMethod(operationName = "GetStations", action = "TrainViewServiceNs/TrainViewService/GetStations")
    @WebResult(name = "GetStationsResult", targetNamespace = "TrainViewServiceNs")
    @RequestWrapper(localName = "GetStations", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GetStations")
    @ResponseWrapper(localName = "GetStationsResponse", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GetStationsResponse")
    public ArrayOfStation getStations();

    /**
     * 
     * @param lastTimestamp
     * @return
     *     returns smartcampus.service.trentomale.wsclient.TrainListTransport
     */
    @WebMethod(operationName = "GetTrains", action = "TrainViewServiceNs/TrainViewService/GetTrains")
    @WebResult(name = "GetTrainsResult", targetNamespace = "TrainViewServiceNs")
    @RequestWrapper(localName = "GetTrains", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GetTrains")
    @ResponseWrapper(localName = "GetTrainsResponse", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GetTrainsResponse")
    public TrainListTransport getTrains(
        @WebParam(name = "lastTimestamp", targetNamespace = "TrainViewServiceNs")
        XMLGregorianCalendar lastTimestamp);

}
