
package smartcampus.service.trentomale.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrainViewService", targetNamespace = "TrainViewServiceNs")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrainViewService {


    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GertServerTime", action = "TrainViewServiceNs/TrainViewService/GertServerTime")
    @WebResult(name = "GertServerTimeResult", targetNamespace = "TrainViewServiceNs")
    @RequestWrapper(localName = "GertServerTime", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GertServerTime")
    @ResponseWrapper(localName = "GertServerTimeResponse", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GertServerTimeResponse")
    public XMLGregorianCalendar gertServerTime();

    /**
     * 
     * @return
     *     returns smartcampus.service.trentomale.wsclient.ArrayOfStation
     */
    @WebMethod(operationName = "GetStations", action = "TrainViewServiceNs/TrainViewService/GetStations")
    @WebResult(name = "GetStationsResult", targetNamespace = "TrainViewServiceNs")
    @RequestWrapper(localName = "GetStations", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GetStations")
    @ResponseWrapper(localName = "GetStationsResponse", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GetStationsResponse")
    public ArrayOfStation getStations();

    /**
     * 
     * @param lastTimestamp
     * @return
     *     returns smartcampus.service.trentomale.wsclient.TrainListTransport
     */
    @WebMethod(operationName = "GetTrains", action = "TrainViewServiceNs/TrainViewService/GetTrains")
    @WebResult(name = "GetTrainsResult", targetNamespace = "TrainViewServiceNs")
    @RequestWrapper(localName = "GetTrains", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GetTrains")
    @ResponseWrapper(localName = "GetTrainsResponse", targetNamespace = "TrainViewServiceNs", className = "smartcampus.service.trentomale.wsclient.GetTrainsResponse")
    public TrainListTransport getTrains(
        @WebParam(name = "lastTimestamp", targetNamespace = "TrainViewServiceNs")
        XMLGregorianCalendar lastTimestamp);

}
