/*******************************************************************************
 * Copyright 2012-2013 Trento RISE
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 ******************************************************************************/
package smartcampus.service.trentomale.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrainViewService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://trainview.algorab.net/TrainViewService.svc?wsdl")
public class TrainViewService_Service
    extends Service
{

    private final static URL TRAINVIEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRAINVIEWSERVICE_EXCEPTION;
    private final static QName TRAINVIEWSERVICE_QNAME = new QName("http://tempuri.org/", "TrainViewService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://trainview.algorab.net/TrainViewService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRAINVIEWSERVICE_WSDL_LOCATION = url;
        TRAINVIEWSERVICE_EXCEPTION = e;
    }

    public TrainViewService_Service() {
        super(__getWsdlLocation(), TRAINVIEWSERVICE_QNAME);
    }

    public TrainViewService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRAINVIEWSERVICE_QNAME);
    }

    public TrainViewService_Service(URL wsdlLocation) {
        super(wsdlLocation, TRAINVIEWSERVICE_QNAME);
    }

    public TrainViewService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRAINVIEWSERVICE_QNAME);
    }

    public TrainViewService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrainViewService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns TrainViewService
     */
    @WebEndpoint(name = "BasicHttpBinding_TrainViewService")
    public TrainViewService getBasicHttpBindingTrainViewService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_TrainViewService"), TrainViewService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrainViewService
     */
    @WebEndpoint(name = "BasicHttpBinding_TrainViewService")
    public TrainViewService getBasicHttpBindingTrainViewService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_TrainViewService"), TrainViewService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAINVIEWSERVICE_EXCEPTION!= null) {
            throw TRAINVIEWSERVICE_EXCEPTION;
        }
        return TRAINVIEWSERVICE_WSDL_LOCATION;
    }

}
